site_name: Desinfect
theme:
  name: material
  language: de
  font: false
  custom_dir: web/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dunkles Farbschema aktivieren
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Helles Farbschema aktivieren
plugins:
  - search:
      lang: de
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
extra_css:
  - assets/stylesheets/extra.css
nav:
  - Start: index.md
  - Handdesinfektion: Handdesinfektion.md
  - Flächendesinfektion: Flaechendesinfektion.md
  - Kategorien: Kategorien.md
  - Anleitungen:
      - Übersicht: Anleitungen/index.md
  - Sortierbare Tabelle: Tabelle.md
  - Bulletins:
      - Übersicht: Bulletins/index.md
  - Methodik:
      - Wirksamkeit: Methodik/Wirksamkeit.md
      - Bewertung: Methodik/Bewertung.md
      - Sicherheit: Methodik/Sicherheit.md
not_in_nav: |
  /WARTUNG.md
  /Wartung/
